// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('signUpOrganizerTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('signUpOrganizerTest', async function() {
    // Test name: signUpOrganizerTest
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://localhost:4200/login")
    // 2 | setWindowSize | 945x905 | 
    await driver.manage().window().setRect(945, 905)
    // 3 | click | css=.cdk-focused > .mat-button-wrapper | 
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
  })
})
