// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('signUpUser', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('signUpUser', async function() {
    // Test name: signUpUser
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://localhost:4200/login")
    // 2 | setWindowSize | 945x905 | 
    await driver.manage().window().setRect(945, 905)
    // 3 | mouseOver | linkText=Sign Up | 
    {
      const element = await driver.findElement(By.linkText("Sign Up"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | click | linkText=Sign Up | 
    await driver.findElement(By.linkText("Sign Up")).click()
    // 5 | mouseOut | linkText=Sign Up | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 6 | click | css=p | 
    await driver.findElement(By.css("p")).click()
  })
})
