// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SignInOrganizerTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SignInOrganizerTest', async function() {
    // Test name: SignInOrganizerTest
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://localhost:4200/login")
    // 2 | setWindowSize | 945x905 | 
    await driver.manage().window().setRect(945, 905)
    // 3 | click | id=inlineRadio1 | 
    await driver.findElement(By.id("inlineRadio1")).click()
    // 4 | click | css=.ng-tns-c85-0 > .mat-form-field-infix | 
    await driver.findElement(By.css(".ng-tns-c85-0 > .mat-form-field-infix")).click()
    // 5 | type | id=mat-input-0 | organizer@prueba.com
    await driver.findElement(By.id("mat-input-0")).sendKeys("organizer@prueba.com")
    // 6 | sendKeys | id=mat-input-0 | ${KEY_DOWN}
    await driver.findElement(By.id("mat-input-0")).sendKeys(Key.DOWN)
    // 7 | type | id=mat-input-0 | organizer@prueba.com
    await driver.findElement(By.id("mat-input-0")).sendKeys("organizer@prueba.com")
    // 8 | click | id=mat-input-1 | 
    await driver.findElement(By.id("mat-input-1")).click()
    // 9 | type | id=mat-input-1 | organizer
    await driver.findElement(By.id("mat-input-1")).sendKeys("organizer")
    // 10 | click | css=.mat-raised-button > .mat-button-wrapper | 
    await driver.findElement(By.css(".mat-raised-button > .mat-button-wrapper")).click()
  })
})
